version: "3.8"

services:
        mongo:
                image: mongo:4.4
                volumes:
                        - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
                        - ./todo-backend/mongo_prod_data:/data/db
                environment:
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: example
                        MONGO_INITDB_DATABASE: the_database

        redis:
                image: redis
                volumes:
                        - ./todo-backend/redis_prod_data:/data
                command: ['redis-server', '--appendonly', 'yes']

        express-app:
                image: todo-backend-prod
                build:
                        context: ./todo-backend
                        dockerfile: Dockerfile
                environment:
                        - REDIS_URL=redis://redis:6379
                        - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
                container_name: todo-backend-prod
                        
        react-app:
                image: todo-frontend-prod
                build:
                        context: ./todo-frontend
                        dockerfile: Dockerfile

                environment:
                        - REACT_APP_BACKEND_URL=/api/
                container_name: todo-frontend-prod
                depends_on:
                        - express-app
        nginx:
                image: nginx:1.20-alpine
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf:ro
                ports:
                        - 8080:80
                container_name: reverse-proxy
                depends_on:
                        - express-app
                        - react-app
